version: '3.8'

services:
  # Tu backend FastAPI actual
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: brand_detection_backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - ENV=development
      - DEBUG=1
    networks:
      - brand_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Streamlit
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brand_detection_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - brand_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  brand_network:
    driver: bridge

# Volúmenes para persistencia de datos
volumes:
  models_data:
  uploads_data: